url: https://www.fakenewsbears.org
baseurl:

# Site settings
title: Fake News Bears
email: aiwamizu@berkeley.edu
description: "Repository for UC Berkeley MIDS Capstone Project (Spring 2023) for team Fake News Bears looking at US politician Twitter data to assess the spread of and exposure to disinformation online."


# Team names, titles and social links
people:
- name: Akiko Iwamizu
  pic: 1
  position: SME & App Development
  social:
    - title: gmail
      url: #mailto:{{akikoiwamizu@gmail.com}}
    - title: github
      url: #https://github.com/akikoiwamizu/
    - title: linkedin
      url: #https://www.linkedin.com/in/akikoiwamizu/

- name: Brook Bi
  pic: 2
  position: Project Management
  social:
    - title: email
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Giorgio Soggiu
  pic: 3
  position: Exploratory Data Analysis
  social:
    - title: email
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Jason Yang
  pic: 4
  position: Product Management
  social:
    - title: email
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Razal Minhas
  pic: 5
  position: ML Engineering
  social:
    - title: email
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Rohin Chabra
  pic: 6
  position: Data Engineering
  social:
    - title: email
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #

# Build settings
markdown: kramdown
permalink: pretty
