url: https://www.fakenewsbears.org
baseurl:

# Site settings
title: Fake News Bears
email: aiwamizu@berkeley.edu
description: "Repository for UC Berkeley MIDS Capstone Project (Spring 2023) for team Fake News Bears looking at US politician Twitter data to assess the spread of and exposure to disinformation online."


# Team names, titles and social links
people:
- name: Akiko Iwamizu
  pic: 1
  position: SME & App Development
  social:
    - title: google-plus
      url: mailto:aiwamizu@berkeley.edu
    - title: github
      url: https://github.com/akikoiwamizu/
    - title: linkedin
      url: https://www.linkedin.com/in/akikoiwamizu/

- name: Brook Bi
  pic: 2
  position: Project Management
  social:
    - title: google-plus
      url: mailto:brook.bi@berkeley.edu
    - title: github
      url: https://github.com/brookbi
    - title: linkedin
      url: https://www.linkedin.com/in/brook-bi/

- name: Giorgio Soggiu
  pic: 3
  position: Exploratory Data Analysis
  social:
    - title: google-plus
      url: mailto:soggiugiorgio@berkeley.edu
    - title: github
      url: https://soggiugiorgio.github.io/
    - title: linkedin
      url: https://www.linkedin.com/in/giorgio-soggiu/

- name: Jason Yang
  pic: 4
  position: Product Management
  social:
    - title: google-plus
      url: mailto:chiaojyang@berkeley.edu
    - title: github
      url: https://github.com/jasonwithcoffee
    - title: linkedin
      url: https://www.linkedin.com/in/jasonwithcoffee/

- name: Razal Minhas
  pic: 5
  position: ML Engineering
  social:
    - title: google-plus
      url: mailto:razal@berkeley.edu
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Rohin Chabra
  pic: 6
  position: Data Engineering
  social:
    - title: google-plus
      url: mailto:rchabra@berkeley.edu
    - title: github
      url: https://github.com/rchabra
    - title: linkedin
      url: https://www.linkedin.com/in/rohin-chabra-11800368/

# Build settings
markdown: kramdown
permalink: pretty
